services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector
    networks:
      - backend-infra-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./resources/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend-infra-network

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    ports:
      - "4318:4318"
    volumes:
      - ./resources/otel-config.yml:/etc/otelcol/config.yaml
    command: ["--config=/etc/otelcol/config.yaml"]
    depends_on:
      - jaeger
    networks:
      - backend-infra-network

  jaeger:
    image: jaegertracing/jaeger:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4318"
    networks:
      - backend-infra-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - prometheus
      - jaeger
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./resources/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./resources/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - backend-infra-network

volumes:
  grafana-data:
    name: grafana-data

networks:
  backend-infra-network:
    driver: bridge