services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector
    networks:
      - backend-infra-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./resources/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend-infra-network

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    ports:
      - "4318:4318"  # Expose port 4318 on host
    volumes:
      - ./resources/otel-config.yml:/etc/otelcol/config.yaml  # Correct default path
    command: ["--config=/etc/otelcol/config.yaml"]
    depends_on:
      - jaeger
    networks:
      - backend-infra-network

  jaeger:
    image: jaegertracing/jaeger:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4318"
    networks:
      - backend-infra-network

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   depends_on:
  #     - prometheus
  #     - jaeger
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - backend-infra-network

networks:
  backend-infra-network:
    driver: bridge