version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5432:5432"
    networks:
      - backend-infra-network

  prometheus:
    image: prom/prometheus:v3.3.1
    depends_on:
      - app
    volumes:
      - ./resources/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend-infra-network

  jaeger:
    image: jaegertracing/all-in-one:1.68.0
    depends_on:
      - app
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - backend-infra-network

  grafana:
    image: grafana/grafana:11.6.1
    depends_on:
      - prometheus
      - jaeger
    ports:
      - "3000:3000"
    networks:
      - backend-infra-network

networks:
  backend-infra-network:
    driver: bridge