receivers:
  otlp:
    protocols:
      http:
        endpoint: otel-collector:4318

exporters:
  otlphttp/jaeger:
    endpoint: http://jaeger:4318/
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp/jaeger]
